### ISSUE TITLE
Two frequency tables Sam Tator and Praanshu Adiga

### ISSUE THREAD

**Issue by Bman6854** [Bman6854/QMB-210-10-TEAM-3-#14]

**Comment by Bman6854** [comment]
how are you guys doing

**Comment by praanshad** [comment]
Thank you Sam! I appreciate you doing both of it.

**Comment by praanshad** [comment]
[

https://github.com/Bman6854/QMB-210-10-TEAM-3-/assets/145412933/235e573b-e9e4-4a82-bdf7-c5353e36026e

](url)
