### ISSUE TITLE
One contingency table Rachel Riemersma Rachel Riemersma and Alexis Alegre-Castro

### ISSUE THREAD

**Issue by Bman6854** [Bman6854/QMB-210-10-TEAM-3-#16]

**Comment by Bman6854** [comment]
how are you guys doing

**Comment by alexisstatsclass** [comment]
Hey brennan, I have finished the table and its in the excel document. Only thing we have left is to update the power point slides! Get it to you by EOD.

**Comment by Bman6854** [comment]
perfect let me know if i can do anything to help

**Comment by alexisstatsclass** [comment]
Hey Brennan, the PP slide has been updated and completed
