### ISSUE TITLE
Two bar charts Chloe Poczatek and Trevor B

### ISSUE THREAD

**Issue by Bman6854** [Bman6854/QMB-210-10-TEAM-3-#18]

**Comment by Bman6854** [comment]
how are you guys doing

**Comment by Treevor-B** [comment]
We have completed our Bar charts and are working on the questions for them

**Comment by alyssa-riv** [comment]
Good! I completed two bar charts for questions 4 and 9. I also uploaded the two charts onto a powerpoint slide. Just have to elaborate on them, that's all.

**Comment by chloepoczatek** [comment]
Good! We completed our bar charts and uploaded them to the power point slide, now we are just working on the questions in the power point.
