### ISSUE TITLE
SURVEY QUESTION Atticus A. Bartlett

### ISSUE THREAD

**Issue by Bman6854** [Bman6854/QMB-210-10-TEAM-3-#3]

**Comment by atticus32** [comment]
Have you ever considered studying abroad?

If no, what are the main reasons why you haven't considered studying abroad? (Select all that apply)
 -Financial concerns
 -Lack of awareness about study abroad programs
 -Concerns about language barriers
 -Family obligations
 -Academic commitments
 -Personal preferences (please specify)
 -Other (please specify)

If you were to travel abroad, what program would you be most willing to choose? 
- Abroad for a few weeks (for one class)
- A whole semester abroad (for multiple classes) 

Where you be the most inclined to travel to if you were to travel abroad? 
- (Provide an other section also) 

How easy (or difficult) is it to register for a study abroad program? 
-Very easy 
-Easy
-Somewhat easy
-Somewhat difficult
-Difficult
-Very Difficult

What are your expectations for the cultural and personal experiences you hope to gain from studying abroad? (Select all that apply)
 -Learning a new language
 -Immersing in a different culture
 -Making international friends
 -Gaining a global perspective
 -Exploring new places
 -Career advancement
 -Personal growth
 -Other (please specify)

If you have studied abroad how satisfied were you with your experience registering? 
-Very Dissatisfied
-Dissatisfied
-Neutral
-Satisfied
-Very Satisfied

If you have studied abroad how satisfied are you with your experience of the program? 
-Very Dissatisfied
-Dissatisfied
-Neutral
-Satisfied
-Very Satisfied

If you are studying abroad or have studied abroad, what major do you have declared?
- An international one 
- Not an international one
